[tool.poetry]
name = "pysigma-backend-ala"
version = "0.1.0"
description = "pySigma Ala backend"
authors = ["SOC Prime Team"]
license = "LGPL-2.1-only"
repository = "https://<repo_id>"
packages = [
    { include = "sigma" }
]

[tool.poetry.dependencies]
python = "^3.8"
pysigma = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pysigma-pipeline-sysmon = "^0.1.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
